
# makeCacheMatrix generates a list that contains the functions to 
# set the value of the matrix in the list
# get the value of the matrix from the list
# calculate and set the inverse of the matrix x (solve) 
# get the inverse of matrix x from the list 
makeCacheMatrix <- function(x = matrix()) {
    i <- NULL
    set <- function(y) {
        x <<- y
        i <<- NULL
    }
    get <- function() x
    setinverse <- function(solve) i <<- solve
    getinverse <- function() i
    list(set = set, get = get,
         setinverse = setinverse,
         getinverse = getinverse)

}


# cacheSolve will calculate the inverse matrix x and store it in the list 
# that is generated by makeCacheMatrix() above only if the inverse has not
# been calculated (and stored in the list) yet
cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    i <- x$getinverse()
    if(!is.null(i)) {
        message("getting cached data")
        return(i)
    }
    data <- x$get()
    i <- solve(data, ...)
    x$setinverse(i)
    i
}
